services:
  go-connect-backend:
    build:
      context: ./
      dockerfile: ./go-connect-backend/Dockerfile
    ports:
      - '8081:8081'
    environment:
      - DB_HOST=pg
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=person_db

    depends_on:
      - pg

    # networks:
    #   - app-network

  # Backend Rust gRPC server
  rust-grpc-backend:
    build:
      context: ./
      dockerfile: ./rust-grpc-backend/Dockerfile
    ports:
      - '50051:50051'
    environment:
      - DATABASE_URL=postgres://user:password@pg:5432/person_db
    depends_on:
      - pg

    # networks:
    #   - app-network

  # # Frontend React TypeScript app
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - go-connect-backend
      - rust-grpc-backend
    # networks:
    #   - app-network

  # Envoy proxy for gRPC-Web support
  envoy:
    image: envoyproxy/envoy:v1.33-latest
    ports:
      - '8080:8080'
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    # command: ['-c', '/etc/envoy/envoy.yaml']
    # networks:
    # - app-network

  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: person_db
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
# networks:
#   app-network:

volumes:
  pg_data:
